version: "2"
checks:
  file-lines:
    config:
      threshold: 200
  method-complexity:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
exclude_patterns:
- "**/node_modules/"
- "test/"
- "**/*.d.ts"
- "**/*.js"